service: nodejs

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get

plugins:
  - serverless-offline
  - serverless-domain-manager

# if you want to set custom domain
# you must to set custom fields
#custom:
#  customDomain:
#    basePath: ''
#    domainName: {YOUR_DOMAIN_NAME}
#    stage: ${self:provider.stage}
#    certificateName: {YOUR_CERTIFICATE_NAME}
#    createRoute53Record: true
